export const languages = {
  en: "English",
  mn: "Монгол",
} as const

export type Language = keyof typeof languages

export const translations = {
  en: {
    // Navigation
    nav: {
      home: "Home",
      courses: "Courses",
      videos: "Videos",
      login: "Login",
      register: "Register",
      dashboard: "Dashboard",
      profile: "Profile",
      settings: "Settings",
      logout: "Logout",
      careers: "Careers",
      navigation: "Navigation",
      contacts: "Contacts",
    },
    // Home page
    home: {
      hero: {
        title: "Learn. <span style='color: #FF344A;'>Create.</span> Get Hired.",
        subtitle: "Empower yourself with practical digital skills in marketing, design, and AI. Join Mongolia's premier academy for digital professionals.",
        motto: "Digital marketing, sales, graphic design, artificial intelligence's most innovative programs",
        studentsHired: "Students Hired:",
        startLearning: "Start Learning Today",
        viewCourses: "View All Courses",
      },
      courses: {
        title: "Available Courses",
        subtitle: "Start your learning journey with our professional courses",
        viewAll: "View All Courses",
        noEnrollment: "You haven't enrolled in any courses yet",
        noEnrollmentDescription: "Interested in our courses? Visit the courses page to see all available courses and start your learning journey.",
        browseCourses: "Browse Courses",
        enrolled: "Enrolled",
        continueLearning: "Continue Learning",
      },
      benefits: {
        title: "Why Win Academy?",
        subtitle: "Built for Mongolia's digital future",
        skills: {
          title: "Skills that Matter",
          description: "Courses designed for real-world jobs in Mongolia's growing digital economy.",
        },
        growth: {
          title: "Faster Growth",
          description: "Learn, practice, and get hired quickly with our accelerated learning approach.",
        },
        ai: {
          title: "Powered by AI",
          description: "Stay ahead with cutting-edge AI tools and techniques integrated into every course.",
        },
      },
      testimonials: {
        title: "Success Stories",
        subtitle: "Hear from our graduates who transformed their careers",
        batbayar: {
          role: "Digital Marketing Specialist",
          content: "Win Academy helped me land my dream job at a top marketing agency. The practical skills I learned were exactly what employers were looking for.",
        },
        oyunaa: {
          role: "Freelance Designer",
          content: "The UI/UX course transformed my career. I went from zero design experience to earning ₮2M+ monthly as a freelancer.",
        },
        munkh: {
          role: "AI Consultant",
          content: "The AI tools course gave me the edge I needed. Now I help businesses automate their processes and increase efficiency.",
        },
      },
      contact: {
        title: "Get in Touch",
        subtitle: "Ready to start your digital transformation? Contact us today.",
        location: "Pearl Tower B Corpus",
        floor: "11th Floor, Room 1101",
        city: "Ulaanbaatar, Mongolia",
        phone: "9016-6060, 9668-0707",
        email: "hello@winacademy.mn",
      },
    },
    // Courses page
    courses: {
      title: "All Courses",
      subtitle: "Choose from online and on-site courses",
      search: "Search courses...",
      filter: "Filter by modality",
      online: "Online",
      onsite: "On-site",
      hybrid: "Hybrid",
      all: "All",
      coursesFound: "courses found",
      onlineCourses: "Online courses",
      onsiteCourses: "On-site courses",
      previous: "Previous",
      next: "Next",
      beginner: "Beginner",
      intermediate: "Intermediate",
      advanced: "Advanced",
      noCourses: "No courses available yet",
      noCoursesDescription: "Our teachers are currently preparing courses. New courses will be added soon.",
    },
    // Course cards
    courseCard: {
      enrollNow: "Enroll Now",
      continue: "Continue",
      duration: "Duration",
      instructor: "Instructor",
      schedule: "Schedule",
    },
    // Auth pages
    auth: {
      login: {
        title: "Welcome Back",
        subtitle: "Sign in to continue your learning journey",
        email: "Email Address",
        password: "Password",
        emailPlaceholder: "Enter your email",
        passwordPlaceholder: "Enter your password",
        rememberMe: "Remember me",
        forgotPassword: "Forgot your password?",
        signIn: "Sign In",
        googleSignIn: "Continue with Google",
        noAccount: "Don't have an account?",
        signUp: "Sign up",
        or: "or",
        authenticationRequired: "Authentication Required",
        authenticationRequiredDescription: "You need to be authenticated to access the dashboard.",
        goToLogin: "Go to Login",
        // Error messages
        emailRequired: "Email is required",
        emailInvalid: "Please enter a valid email address",
        passwordRequired: "Password is required",
        invalidCredentials: "Invalid email or password. Please try again.",
        unexpectedError: "An unexpected error occurred. Please try again.",
      },
      register: {
        title: "Create Account",
        subtitle: "Start your learning journey today",
        fullName: "Full Name",
        email: "Email Address",
        phone: "Phone Number",
        password: "Password",
        confirmPassword: "Confirm Password",
        fullNamePlaceholder: "Enter your full name",
        emailPlaceholder: "Enter your email",
        phonePlaceholder: "Enter your phone number",
        passwordPlaceholder: "Create a password",
        confirmPasswordPlaceholder: "Confirm your password",
        agreeToTerms: "I agree to the Terms and Conditions and Privacy Policy",
        agreeToTermsText: "I agree to the",
        and: "and",
        terms: "Terms of Service",
        privacy: "Privacy Policy",
        createAccount: "Create Account",
        creating: "Creating Account...",
        googleSignUp: "Sign up with Google",
        or: "or",
        haveAccount: "Already have an account?",
        signIn: "Sign in",
        // Error messages
        fullNameRequired: "Full name is required",
        emailRequired: "Email is required",
        emailInvalid: "Please enter a valid email address",
        phoneRequired: "Phone number is required",
        phoneInvalid: "Please enter a valid phone number",
        passwordRequired: "Password is required",
        passwordTooShort: "Password must be at least 6 characters long",
        confirmPasswordRequired: "Please confirm your password",
        passwordMismatch: "Passwords do not match",
        agreeToTermsRequired: "You must agree to the terms and conditions",
        registrationFailed: "Registration failed. Please try again.",
        emailAlreadyExists: "This email address is already registered. Please use a different email or try logging in.",
        loginAfterRegisterFailed: "Registration successful but login failed. Please try logging in.",
        unexpectedError: "An unexpected error occurred. Please try again.",
        googleSignUpFailed: "Google sign-up failed. Please try again.",
      },
    },
    // Checkout
    checkout: {
      title: "Checkout Information",
      orderSummary: "Order Summary",
      contactInfo: "Contact Information",
      paymentMethod: "Payment Method",
      qpay: "QPay (Mobile Payment)",
      byl: "BYL (Bank Transfer)",
      terms: "I agree to the Terms and Conditions and Privacy Policy",
      pay: "Pay",
      processing: "Processing...",
      // Error messages
      emailAlreadyRegistered: "This email is already registered with another account. Please use a different email or sign in to your existing account.",
      userAlreadyExists: "A user with this email already exists. Please use a different email address.",
    },
    // Payment
    payment: {
      success: {
        title: "Payment Successful!",
        description: "Your enrollment has been confirmed. You can now access your course.",
        goToDashboard: "Go to Dashboard",
        tryAgain: "Try Again",
        backToHome: "Back to Home",
        autoUpdate: "This page will automatically update when your payment is processed.",
      },
      pending: {
        title: "Payment Pending",
        description: "Your payment is being processed. This may take a few minutes.",
      },
      failed: {
        title: "Payment Failed",
        description: "Your payment could not be processed. Please try again or contact support.",
      },
      cancelled: {
        title: "Payment Cancelled",
        description: "Your payment was cancelled. You can try again or choose a different payment method.",
      },
    },
    // Admin
    admin: {
      title: "Admin Management",
      dashboard: "Dashboard",
      courses: "Courses",
      users: "Users",
      orders: "Orders",
      analytics: "Analytics",
      logout: "Logout",
    },
    // Common
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
      cancel: "Cancel",
      save: "Save",
      edit: "Edit",
      delete: "Delete",
      back: "Back",
      next: "Next",
      submit: "Submit",
      close: "Close",
      details: "Details",
    },
  },
  mn: {
    // Navigation
    nav: {
      home: "Нүүр",
      courses: "Сургалтууд",
      videos: "Видеонууд",
      login: "Нэвтрэх",
      register: "Бүртгүүлэх",
      dashboard: "Удирдлага",
      profile: "Профайл",
      settings: "Тохиргоо",
      logout: "Гарах",
      careers: "Карьер",
      navigation: "Хөтөч",
      contacts: "Холбоо барих",
    },
    // Home page
    home: {
      hero: {
        title: "Суралц. <span style='color: #FF344A;'>Бүтээ.</span> Ажилд ор.",
        subtitle: "Маркетинг, дизайн, AI-ийн практик ур чадвараар өөрийгөө хөгжүүл. Монголын тэргүүлэгч дижитал мэргэжлийн академид нэгдээрэй.",
        motto: "Дижитал маркетинг, борлуулалт, график дизайн, хиймэл оюуны хамгийн шинэлэг хөтөлбөрүүд",
        studentsHired: "Ажилд орсон сурагчид:",
        startLearning: "Өнөөдөр суралцаж эхлээрэй",
        viewCourses: "Бүх сургалтыг харах",
      },
      courses: {
        title: "Боломжит сургалтууд",
        subtitle: "Манай мэргэжлийн сургалтуудаар сургалтын аялаа эхлээрэй",
        viewAll: "Бүх сургалтыг харах",
        noEnrollment: "Та одоогоор сургалт худалдаж аваагүй байна",
        noEnrollmentDescription: "Танд одоогоор худалдаж авсан сургалт байхгүй байна. Манай сургалтуудас худалдаж авахыг хүсэвэл энд дарна уу.",
        browseCourses: "Сургалтуудыг харах",
        enrolled: "Худалдан авсан",
        continueLearning: "Үргэлжлүүлэх",
      },
      benefits: {
        title: "Яагаад WIN Academy?",
        subtitle: "Монголын дижитал ирээдүйн төлөө бүтээгдсэн",
        skills: {
          title: "Чухал ур чадварууд",
          description: "Монголын хөгжиж буй дижитал эдийн засгийн бодит ажлын байрны төлөө зориулсан сургалтууд.",
        },
        growth: {
          title: "Хурдан хөгжил",
          description: "Манай хурдасгасан сургалтын аргаар суралцаж, дадлага хийж, хурдан ажилд орох боломж.",
        },
        ai: {
          title: "AI-хөгжүүлэлт",
          description: "Одоо үед хэрэгцээтэй AI чанартай хэрэглэх аргачлалууд.",
        },
      },
      testimonials: {
        title: "Амжилтын түүхүүд",
        subtitle: "Карьераа өөрчилсөн төгсөгчдийнхээ түүхийг сонсоорой",
        batbayar: {
          role: "Дижитал маркетингийн мэргэжилтэн",
          content: "WIN Academy надад дээд зэргийн маркетингийн агентлагт мөрөөдлийн ажлыг олход тусалсан. Би сурсан практик ур чадварууд нь ажил олгогчдын хайж байсан зүйл байсан.",
        },
        oyunaa: {
          role: "Чөлөөт дизайнер",
          content: "UI/UX сургалт нь миний карьерыг өөрчилсөн. Би тэг дизайн туршлагатай байснаас сая ₮2M+ сарын орлоготой чөлөөт дизайнер болсон.",
        },
        munkh: {
          role: "AI зөвлөгч",
          content: "AI хэрэгслүүдийн сургалт надад шаардлагатай давуу талыг өгсөн. Одоо би бизнесүүдэд үйл явцыг автоматжуулж, үр ашгийг нэмэгдүүлэхэд тусалдаг.",
        },
      },
      contact: {
        title: "Холбоо барих",
        subtitle: "",
        location: "Pearl Tower B Corpus",
        floor: "11 давхарт 1101 тоот",
        city: "Улаанбаатар, Монгол",
        phone: "9016-6060, 9668-0707",
        email: "hello@winacademy.mn",
      },
    },
    // Courses page
    courses: {
      title: "Бүх сургалтууд",
      subtitle: "Онлайн болон танхимын сургалтуудаас сонгоорой",
      search: "Сургалт хайх...",
      filter: "Хэлбэрээр шүүх",
      online: "Онлайн",
      onsite: "Танхим",
      hybrid: "Холимог",
      all: "Бүгд",
      coursesFound: "сургалт олдлоо",
      onlineCourses: "Онлайн сургалтууд",
      onsiteCourses: "Танхимын сургалтууд",
      previous: "Өмнөх",
      next: "Дараах",
      beginner: "Анхан шат",
      intermediate: "Дунд",
      advanced: "Дээд",
      noCourses: "Одоогоор сургалт байхгүй байна",
      noCoursesDescription: "Манай багш нар одоогоор сургалтуудыг бэлтгэж байна. Удахгүй шинэ сургалтууд нэмэгдэх болно.",
    },
    // Course cards
    courseCard: {
      enrollNow: "Худалдаж авах",
      continue: "Үргэлжлүүлэх",
      duration: "Үргэлжлэх хугацаа",
      instructor: "Багш",
      schedule: "Хуваарь",
    },
    // Auth pages
    auth: {
      login: {
        title: "Сайн байна уу",
        subtitle: "Үргэлжлүүлэн суралцахын тулд бүртгэлдээ нэвтэрнэ үү",
        email: "И-мэйл хаяг",
        password: "Нууц үг",
        emailPlaceholder: "И-мэйл хаягаа оруулна уу",
        passwordPlaceholder: "Нууц үгээ оруулна уу",
        rememberMe: "Намайг сана",
        forgotPassword: "Нууц үгээ мартсан уу?",
        signIn: "Нэвтрэх",
        googleSignIn: "Google-аар үргэлжлүүлэх",
        noAccount: "Бүртгэл байхгүй юу?",
        signUp: "Бүртгүүлэх",
        or: "эсвэл",
        authenticationRequired: "Нэвтрэх шаардлагатай",
        authenticationRequiredDescription: "Хяналтын самбар руу хандахын тулд нэвтэрсэн байх шаардлагатай.",
        goToLogin: "Нэвтрэх хэсэг рүү очих",
        // Error messages
        emailRequired: "И-мэйл хаяг оруулах шаардлагатай",
        emailInvalid: "Зөв и-мэйл хаяг оруулна уу",
        passwordRequired: "Нууц үг оруулах шаардлагатай",
        invalidCredentials: "И-мэйл эсвэл нууц үг буруу байна. Дахин оролдоно уу.",
        unexpectedError: "Санаандгүй алдаа гарлаа. Дахин оролдоно уу.",
      },
      register: {
        title: "Бүртгэл үүсгэх",
        subtitle: "Өнөөдөр суралцаж эхлээрэй",
        fullName: "Бүтэн нэр",
        email: "И-мэйл хаяг",
        phone: "Утасны дугаар",
        password: "Нууц үг",
        confirmPassword: "Нууц үг баталгаажуулах",
        fullNamePlaceholder: "Бүтэн нэрээ оруулна уу",
        emailPlaceholder: "И-мэйл хаягаа оруулна уу",
        phonePlaceholder: "Утасны дугаараа оруулна уу",
        passwordPlaceholder: "Нууц үг үүсгэнэ үү",
        confirmPasswordPlaceholder: "Нууц үгээ дахин оруулна уу",
        agreeToTerms: "Би Үйлчилгээний нөхцөл ба Нууцлалын бодлогод зөвшөөрч байна",
        agreeToTermsText: "Би зөвшөөрч байна",
        and: "ба",
        terms: "Үйлчилгээний нөхцөл",
        privacy: "Нууцлалын бодлого",
        createAccount: "Бүртгэл үүсгэх",
        creating: "Бүртгэл үүсгэж байна...",
        googleSignUp: "Google-аар бүртгүүлэх",
        or: "эсвэл",
        haveAccount: "Бүртгэл байгаа юу?",
        signIn: "Нэвтрэх",
        // Error messages
        fullNameRequired: "Бүтэн нэр оруулах шаардлагатай",
        emailRequired: "И-мэйл хаяг оруулах шаардлагатай",
        emailInvalid: "Зөв и-мэйл хаяг оруулна уу",
        phoneRequired: "Утасны дугаар оруулах шаардлагатай",
        phoneInvalid: "Зөв утасны дугаар оруулна уу",
        passwordRequired: "Нууц үг оруулах шаардлагатай",
        passwordTooShort: "Нууц үг дор хаяж 6 тэмдэгттэй байх ёстой",
        confirmPasswordRequired: "Нууц үгээ баталгаажуулна уу",
        passwordMismatch: "Нууц үг таарахгүй байна",
        agreeToTermsRequired: "Үйлчилгээний нөхцөлд зөвшөөрөх шаардлагатай",
        registrationFailed: "Бүртгэл амжилтгүй. Дахин оролдоно уу.",
        emailAlreadyExists: "Энэ и-мэйл хаяг өмнө нь бүртгэгдсэн байна. Өөр и-мэйл хэрэглэх эсвэл нэвтрэхийг оролдоно уу.",
        loginAfterRegisterFailed: "Бүртгэл амжилттай боловч нэвтрэх амжилтгүй. Нэвтрэхийг оролдоно уу.",
        unexpectedError: "Санаандгүй алдаа гарлаа. Дахин оролдоно уу.",
        googleSignUpFailed: "Google-аар бүртгүүлэх амжилтгүй. Дахин оролдоно уу.",
      },
    },
    // Checkout
    checkout: {
      title: "Төлбөр төлөх мэдээлэл",
      orderSummary: "Захиалгын дүн",
      contactInfo: "Холбоо барих мэдээлэл",
      paymentMethod: "Төлбөр төлөх арга",
      qpay: "QPay (Утасны төлбөр)",
      byl: "BYL (Банкны шилжүүлэг)",
      terms: "Би Үйлчилгээний нөхцөл ба Нууцлалын бодлогод зөвшөөрч байна",
      pay: "Төлөх",
      processing: "Боловсруулж байна...",
      // Error messages
      emailAlreadyRegistered: "Энэ и-мэйл хаяг өөр бүртгэлтэй холбогдсон байна. Өөр и-мэйл хэрэглэх эсвэл одоо байгаа бүртгэлээрээ нэвтэрнэ үү.",
      userAlreadyExists: "Энэ и-мэйл хаягтай хэрэглэгч аль хэдийн байна. Өөр и-мэйл хаяг хэрэглэнэ үү.",
    },
    // Payment
    payment: {
      success: {
        title: "Төлбөр амжилттай!",
        description: "Таны бүртгэл баталгаажлаа. Та одоо сургалтаа хандаж болно.",
        goToDashboard: "Удирдлага руу орох",
        tryAgain: "Дахин оролдох",
        backToHome: "Нүүр рүү буцах",
        autoUpdate: "Таны төлбөр боловсруулагдахад энэ хуудас автоматаар шинэчлэгдэнэ.",
      },
      pending: {
        title: "Төлбөр хүлээгдэж байна",
        description: "Таны төлбөр боловсруулагдаж байна. Энэ нь хэдэн минут шаардаж болно.",
      },
      failed: {
        title: "Төлбөр амжилтгүй",
        description: "Таны төлбөр боловсруулагдаагүй. Дахин оролдоно уу эсвэл дэмжлэгтэй холбогдоно уу.",
      },
      cancelled: {
        title: "Төлбөр цуцлагдсан",
        description: "Таны төлбөр цуцлагдсан. Дахин оролдоно уу эсвэл өөр төлбөр төлөх арга сонгоно уу.",
      },
    },
    // Admin
    admin: {
      title: "Админ удирдлага",
      dashboard: "Удирдлага",
      courses: "Сургалтууд",
      users: "Хэрэглэгчид",
      orders: "Захиалгууд",
      analytics: "Аналитик",
      logout: "Гарах",
    },
    // Common
    common: {
      loading: "Уншиж байна...",
      error: "Алдаа",
      success: "Амжилттай",
      cancel: "Цуцлах",
      save: "Хадгалах",
      edit: "Засах",
      delete: "Устгах",
      back: "Буцах",
      next: "Дараах",
      submit: "Илгээх",
      close: "Хаах",
      details: "Дэлгэрэнгүй",
    },
  },
} as const

export type TranslationKey = keyof typeof translations.en
